/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * @author dell
 */
public class JfResultados extends javax.swing.JFrame {

    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    public JfResultados() {
        initComponents();
        this.setLocationRelativeTo(this);
        //Modelo 1
        modelo= new DefaultTableModel();
        modelo.addColumn("Algoritmo");
        modelo.addColumn("Tiempo Ejecución(ms)");
        modelo.addColumn("Cantidad de Ocurrencias encontradas");   
        //Reflejamos el modelo en la tabla del jframe
        this.jTResultados1.setModel(modelo);
        
        //Modelo 2
        modelo2= new DefaultTableModel();
        modelo2.addColumn("Algoritmo");
        modelo2.addColumn("Tiempo Ejecución(ms)");
        modelo2.addColumn("Cantidad de Ocurrencias encontradas");    
        //Reflejamos el modelo en la tabla del jframe
        this.jTResultados2.setModel(modelo2);
        
        //Centrar el contenido de las celdas de la columna 1
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTResultados1.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        jTResultados2.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
    }
    
    public void agregarDatosLeaked(String nomAlgortimo,long tiempoE, String numVeces){
        String [] Datos= new String[4];
        Datos[0] = nomAlgortimo;
        Datos[1] = ""+tiempoE;
        Datos[2] = numVeces;
        this.modelo.addRow(Datos); //Anadimos los datos
        
        jTResultados1.getColumnModel().getColumn(1).setPreferredWidth(150); //Establecemos en 150 el ancho de la columna 1
        jTResultados1.getColumnModel().getColumn(2).setPreferredWidth(300); //Establecemos en 300 el ancho de la columna 2
        this.jTResultados1.setModel(modelo);
        jTResultados1.setRowHeight(30); //Establecemos la altura de las filas en 30
    }
    
    public void agregarDatosPhisher(String nomAlgortimo,long tiempoE, String numVeces){
        String [] Datos= new String[4];
        Datos[0] = nomAlgortimo;
        Datos[1] = ""+tiempoE;
        Datos[2] = numVeces;
        this.modelo2.addRow(Datos); //Anadimos los datos
        
        jTResultados2.getColumnModel().getColumn(1).setPreferredWidth(150); //Establecemos en 150 el ancho de la columna 1
        jTResultados2.getColumnModel().getColumn(2).setPreferredWidth(300); //Establecemos en 300 el ancho de la columna 2
        this.jTResultados2.setModel(modelo2);
        jTResultados2.setRowHeight(30); //Establecemos la altura de las filas en 30
    }
    public void setValoresFB(String resultados){
        txaFB.setText(resultados);
    }
    public void setValoresKMP(String resultados){
        txaKMP.setText(resultados);
    }
    public void setValoresBM(String resultados){
        txaBM.setText(resultados);
    }
    public void setValoresFB2(String resultados){
        txaFB2.setText(resultados);
    }
    public void setValoresKMP2(String resultados){
        txaKMP2.setText(resultados);
    }
    public void setValoresBM2(String resultados){
        txaBM2.setText(resultados);
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTPGeneral = new javax.swing.JTabbedPane();
        jPLeaked = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaKMP = new javax.swing.JTextArea();
        lblFB = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaFB = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaBM = new javax.swing.JTextArea();
        lblKMP = new javax.swing.JLabel();
        lblBM = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPPhisher = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTResultados2 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaFB2 = new javax.swing.JTextArea();
        lblFB1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txaKMP2 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txaBM2 = new javax.swing.JTextArea();
        lblKMP1 = new javax.swing.JLabel();
        lblBM1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel1.setText("RESULTADOS");

        jTResultados1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTResultados1);

        txaKMP.setColumns(20);
        txaKMP.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txaKMP.setRows(5);
        jScrollPane4.setViewportView(txaKMP);

        lblFB.setText("Fuerza Bruta");

        txaFB.setColumns(20);
        txaFB.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txaFB.setRows(5);
        jScrollPane2.setViewportView(txaFB);

        txaBM.setColumns(20);
        txaBM.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txaBM.setRows(5);
        jScrollPane3.setViewportView(txaBM);

        lblKMP.setText("KMP");

        lblBM.setText("BM");

        javax.swing.GroupLayout jPLeakedLayout = new javax.swing.GroupLayout(jPLeaked);
        jPLeaked.setLayout(jPLeakedLayout);
        jPLeakedLayout.setHorizontalGroup(
            jPLeakedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLeakedLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblFB)
                .addGap(301, 301, 301)
                .addComponent(lblKMP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBM)
                .addGap(159, 159, 159))
            .addGroup(jPLeakedLayout.createSequentialGroup()
                .addGroup(jPLeakedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLeakedLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                    .addGroup(jPLeakedLayout.createSequentialGroup()
                        .addGroup(jPLeakedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPLeakedLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPLeakedLayout.createSequentialGroup()
                                .addGap(386, 386, 386)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPLeakedLayout.setVerticalGroup(
            jPLeakedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLeakedLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPLeakedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFB)
                    .addComponent(lblKMP)
                    .addComponent(lblBM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLeakedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTPGeneral.addTab("LeakedData", jPLeaked);

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel2.setText("RESULTADOS");

        jTResultados2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTResultados2);

        txaFB2.setColumns(20);
        txaFB2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txaFB2.setRows(5);
        jScrollPane6.setViewportView(txaFB2);

        lblFB1.setText("Fuerza Bruta");

        txaKMP2.setColumns(20);
        txaKMP2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txaKMP2.setRows(5);
        jScrollPane7.setViewportView(txaKMP2);

        txaBM2.setColumns(20);
        txaBM2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txaBM2.setRows(5);
        jScrollPane8.setViewportView(txaBM2);

        lblKMP1.setText("KMP");

        lblBM1.setText("BM");

        javax.swing.GroupLayout jPPhisherLayout = new javax.swing.GroupLayout(jPPhisher);
        jPPhisher.setLayout(jPPhisherLayout);
        jPPhisherLayout.setHorizontalGroup(
            jPPhisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPhisherLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblFB1)
                .addGap(294, 294, 294)
                .addComponent(lblKMP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBM1)
                .addGap(153, 153, 153))
            .addGroup(jPPhisherLayout.createSequentialGroup()
                .addGroup(jPPhisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPhisherLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPPhisherLayout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel2)))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(jPPhisherLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane8))
        );
        jPPhisherLayout.setVerticalGroup(
            jPPhisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPhisherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPPhisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFB1)
                    .addComponent(lblBM1)
                    .addComponent(lblKMP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPhisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane8))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(jPPhisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPPhisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTPGeneral.addTab("Phisher", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPGeneral)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPGeneral)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPLeaked;
    private javax.swing.JPanel jPPhisher;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTPGeneral;
    private javax.swing.JTable jTResultados1;
    private javax.swing.JTable jTResultados2;
    private javax.swing.JLabel lblBM;
    private javax.swing.JLabel lblBM1;
    private javax.swing.JLabel lblFB;
    private javax.swing.JLabel lblFB1;
    private javax.swing.JLabel lblKMP;
    private javax.swing.JLabel lblKMP1;
    private javax.swing.JTextArea txaBM;
    private javax.swing.JTextArea txaBM2;
    private javax.swing.JTextArea txaFB;
    private javax.swing.JTextArea txaFB2;
    private javax.swing.JTextArea txaKMP;
    private javax.swing.JTextArea txaKMP2;
    // End of variables declaration//GEN-END:variables
}
